version: '3'

services:
  hadoop-master:
    image: liliasfaxi/spark-hadoop:hv-2.7.2
    container_name: hadoop-master
    hostname: hadoop-master
    networks:
      - hadoop
    ports:
      - "8000:50070"
      - "8088:8088"
      - "707:7077"
    tty: true
    stdin_open: true
    command: ["/bin/bash", "-c", "service ssh start && ./start-hadoop.sh && bash"]

  hadoop-slave1:
    image: liliasfaxi/spark-hadoop:hv-2.7.2
    container_name: hadoop-slave1
    hostname: hadoop-slave1
    networks:
      - hadoop
    ports:
      - "8040:8042"
    tty: true
    stdin_open: true
    command: ["/bin/bash", "-c", "service ssh start && bash"]

  hadoop-slave2:
    image: liliasfaxi/spark-hadoop:hv-2.7.2
    container_name: hadoop-slave2
    hostname: hadoop-slave2
    networks:
      - hadoop
    ports:
      - "8041:8042"
    tty: true
    stdin_open: true
    command: ["/bin/bash", "-c", "service ssh start && bash"]

networks:
  hadoop:
    driver: bridge